[package]
name = "platstar"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
glam = { version = "0.29.2", optional = true}
petgraph = { version = "0.6.5", features=[] }

[features]
2d = ["dep:glam"]

